### ISSUE TITLE
Cricitcal Error in authcheck.php

### ISSUE THREAD

**Issue by ZimmerA** [shibdib/Dramiel#108]
In authcheck.php the bot tries to get 'corpTicker' from the json but it should be 'ticker' this caused all my tickers to be removed. Fixed it by replacing

>  $corpTicker = (string)$corporationDetails['corpTicker'];

on line 335
with:

> $corpTicker = (string)$corporationDetails['ticker'];

**Comment by shibdib** [comment]
Will push something out now thanks!
