### ISSUE TITLE
 Error: vexor not found

### ISSUE THREAD

**Issue by G0wd** [shibdib/Dramiel#119]
Error: vexor not found

While doing a price check.

No errors in logs.

Last version.

**Comment by Maxcraft90** [comment]
![image](https://cloud.githubusercontent.com/assets/20978852/21216393/d8f2835a-c2a6-11e6-9b68-fc7fe693d723.png)

that's how it currenty looks. did you check all 3 logfiles?

**Comment by G0wd** [comment]
Yeah, there is only one file generated, the dramielLog.log.

It was working before the last git pull so I'm confused.

**Comment by G0wd** [comment]
I found this in my php logs:

> Dec 15 10:26:17 php[19211]: PHP Warning:  file_get_contents(): Peer certificate CN=`www.fuzzwork.co.uk' did not match expected CN=`discordapp.com' in /home/discord/dramiel/src/lib/eveApi.php on line 293
> Dec 15 10:26:17 php[19211]: PHP Warning:  file_get_contents(): Failed to enable crypto in /home/discord/dramiel/src/lib/eveApi.php on line 293
> Dec 15 10:26:17 php[19211]: PHP Warning:  file_get_contents(https://www.fuzzwork.co.uk/api/typeid.php?typename=plex): failed to open stream: operation failed in /home/discord/dramiel/src/lib/eveApi.php on line 293
> Dec 15 10:26:17 php[19211]: PHP Warning:  file_get_contents(): Peer certificate CN=`*.tech.ccp.is' did not match expected CN=`discordapp.com' in /home/discord/dramiel/src/lib/eveApi.php on line 254
> Dec 15 10:26:17 php[19211]: PHP Warning:  file_get_contents(): Failed to enable crypto in /home/discord/dramiel/src/lib/eveApi.php on line 254
> Dec 15 10:26:17 php[19211]: PHP Warning:  file_get_contents(https://esi.tech.ccp.is/latest/search/?search=jita&categories=solarsystem&language=en-us&strict=true&datasource=tranquility): failed to open stream: operation failed in /

Did you change something about crypto?

**Comment by shibdib** [comment]
unable to duplicate this anywhere

**Comment by G0wd** [comment]
composer update fixed the problem apparently.
