### ISSUE TITLE
Wardec notification doesn't contain a corp name. 

### ISSUE THREAD

**Issue by smatthews0** [shibdib/Dramiel#136]
* **Problem**: _Whats wrong?_
 Notification doesn't always contain the corp name for a declared wardec

* **Expected**: _What did you expect to happen?_ 
Notification contains the corp which has wardecced us

* **Logs / Screenshots / Proof**: _The more information you give the better!_ 

Eve DramBOT - Last Saturday at 3:05 PM
War with Public-Enemy has been invalidated. Fighting ends in roughly 24 hours.

Eve DramBOT - Last Saturday at 3:21 PM
War with  has been invalidated. Fighting ends in roughly 24 hours.

Eve DramBOT - Today at 6:13 PM
@everyone | War declared by  against The Romulans. Fighting begins in roughly 24 hours.

**Comment by shibdib** [comment]
need the XML or I can't really do anything with it

**Comment by smatthews0** [comment]
Waiting on it to happen again. Will update once i have.

-XML sent directly.
