### ISSUE TITLE
fresh install errors

### ISSUE THREAD

**Issue by MKUltraCorp** [shibdib/Dramiel#16]
Fresh LAMP droplet from Digital Ocean, updated PHP to 5.6.23.  Followed instructions in Wiki, this is what I am getting.

```
root@lamp-nwtl:/etc/supervisor/conf.d# php /home/bots/Dramiel/Dramiel.php
PHP Notice:  Undefined index: guildID in /home/bots/Dramiel/src/plugins/onMessage/auth.php on line 75
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: mapSolarSystems' in /home/bots/Dramiel/src/lib/Db.php:130
Stack trace:
#0 /home/bots/Dramiel/src/lib/Db.php(130): PDO->prepare('SELECT solarSys...')
#1 /home/bots/Dramiel/src/plugins/onMessage/price.php(64): dbQuery('SELECT solarSys...', Array, 'ccp')
#2 /home/bots/Dramiel/Dramiel.php(112): price->init(Array, Object(Discord\Discord), Object(Monolog\Logger))
#3 {main}
  thrown in /home/bots/Dramiel/src/lib/Db.php on line 130
```

**Comment by MKUltraCorp** [comment]
Looks like you are still coding for the old DiscordPHP classes, need to update maybe?  Looks like it was updated at one point but the current code maybe using an old version?

**Comment by MKUltraCorp** [comment]
I commented out the lines for auth and auth check in config.php and that fixed the PHP notice about guildID.  Everything else remains an issue.

**Comment by shibdib** [comment]
try deleting everything in your database folder and restarting.

4.0 of discordPHP breaks the bot as it makes some drastic changes that I don't have time to implement. But that's not causing your issue.

**Comment by shibdib** [comment]
4.0 update was implemented, and a fix for this was as well :)
