### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by scopehs** [shibdib/Dramiel#175]
Hey shib!

I have started using the auth and its been working a charm for named groups within the config.

I have now submitted an API and can see the standings within the sqlitite database, so it know its pulling them.

A have had users auth, be approved, however roles/renaming doesn't seem to work.
It then pulls the user 3 hours after it does a standing check.

The only error thats coming up in the log file is:

PHP Stack trace:
PHP   1. {main}() /home/blah/botdiscord/Dramiel.php:0
PHP   2. Discord\Discord->run() /home/blah/botdiscord/Dramiel.php:296
PHP   3. React\EventLoop\StreamSelectLoop->run() /home/blah/botdiscord/vendor/team-reflex/discord-php/src/Discord/Discord.php:1231
PHP   4. React\EventLoop\Timer\Timers->tick() /home/blah/botdiscord/vendor/react/event-loop/src/StreamSelectLoop.php:177
PHP   5. call_user_func:{/home/blah/botdiscord/vendor/react/event-loop/src/Timer/Timers.php:90}() /home/blah/botdiscord/vendor/react/event-loop/src/Timer/Timers.php:90
PHP   6. {closure:/home/blah/botdiscord/Dramiel.php:172-176}() /home/blah/botdiscord/vendor/react/event-loop/src/Timer/Timers.php:90
PHP   7. getKillmails->tick() /home/blah/botdiscord/Dramiel.php:174
PHP   8. getKillmails->getKM() /home/blah/botdiscord/src/plugins/onTick/getKillmails.php:74
PHP   9. apiTypeName() /home/blah/botdiscord/src/plugins/onTick/getKillmails.php:128
PHP  10. file_get_contents() /home/blah/botdiscord/src/lib/eveApi.php:320
PHP Warning:  file_get_contents(https://esi.tech.ccp.is/latest/universe/types/33475/): failed to open stream: HTTP request failed! HTTP/1.0 500 INTERNAL SERVER ERROR
 in /home/blah/botdiscord/src/lib/eveApi.php on line 320
PHP Stack trace:
PHP   1. {main}() /home/blah/botdiscord/Dramiel.php:0
PHP   2. Discord\Discord->run() /home/blah/botdiscord/Dramiel.php:296
PHP   3. React\EventLoop\StreamSelectLoop->run() /home/blah/botdiscord/vendor/team-reflex/discord-php/src/Discord/Discord.php:1231
PHP   4. React\EventLoop\Timer\Timers->tick() /home/blah/botdiscord/vendor/react/event-loop/src/StreamSelectLoop.php:177
PHP   5. call_user_func:{/home/blah/botdiscord/vendor/react/event-loop/src/Timer/Timers.php:90}() /home/blah/botdiscord/vendor/react/event-loop/src/Timer/Timers.php:90
PHP   6. {closure:/home/blah/botdiscord/Dramiel.php:172-176}() /home/blah/botdiscord/vendor/react/event-loop/src/Timer/Timers.php:90
PHP   7. getKillmails->tick() /home/blah/botdiscord/Dramiel.php:174
PHP   8. getKillmails->getKM() /home/blah/botdiscord/src/plugins/onTick/getKillmails.php:74
PHP   9. apiTypeName() /home/blah/botdiscord/src/plugins/onTick/getKillmails.php:128
PHP  10. file_get_contents() /home/blah/botdiscord/src/lib/eveApi.php:320
PHP Notice:  Undefined index: standings in /home/blah/botdiscord/src/plugins/onTick/authCheck.php on line 211
PHP Stack trace:
PHP   1. {main}() /home/blah/botdiscord/Dramiel.php:0
PHP   2. Discord\Discord->run() /home/blah/botdiscord/Dramiel.php:296
PHP   3. React\EventLoop\StreamSelectLoop->run() /home/blah/botdiscord/vendor/team-reflex/discord-php/src/Discord/Discord.php:1231
PHP   4. React\EventLoop\Timer\Timers->tick() /home/blah/botdiscord/vendor/react/event-loop/src/StreamSelectLoop.php:177
PHP   5. call_user_func:{/home/blah/botdiscord/vendor/react/event-loop/src/Timer/Timers.php:90}() /home/blah/botdiscord/vendor/react/event-loop/src/Timer/Timers.php:90
PHP   6. {closure:/home/blah/botdiscord/Dramiel.php:172-176}() /home/blah/botdiscord/vendor/react/event-loop/src/Timer/Timers.php:90
PHP   7. authCheck->tick() /home/blah/botdiscord/Dramiel.php:174
PHP   8. authCheck->checkPermissions() /home/blah/botdiscord/src/plugins/onTick/authCheck.php:111
PHP Warning:  file_get_contents(https://esi.tech.ccp.is/latest/characters/95022431/): failed to open stream: HTTP request failed! HTTP/1.0 500 INTERNAL SERVER ERROR
 in /home/blah/botdiscord/src/lib/eveApi.php on line 156
PHP Stack trace:
PHP   1. {main}() /home/blah/botdiscord/Dramiel.php:0
PHP   2. Discord\Discord->run() /home/blah/botdiscord/Dramiel.php:296
PHP   3. React\EventLoop\StreamSelectLoop->run() /home/blah/botdiscord/vendor/team-reflex/discord-php/src/Discord/Discord.php:1231
PHP   4. React\EventLoop\Timer\Timers->tick() /home/blah/botdiscord/vendor/react/event-loop/src/StreamSelectLoop.php:177
PHP   5. call_user_func:{/home/blah/botdiscord/vendor/react/event-loop/src/Timer/Timers.php:90}() /home/blah/botdiscord/vendor/react/event-loop/src/Timer/Timers.php:90
PHP   6. {closure:/home/blah/botdiscord/Dramiel.php:172-176}() /home/blah/botdiscord/vendor/react/event-loop/src/Timer/Timers.php:90
PHP   7. authCheck->tick() /home/blah/botdiscord/Dramiel.php:174
PHP   8. authCheck->nameReset() /home/blah/botdiscord/src/plugins/onTick/authCheck.php:123
PHP   9. characterDetails() /home/blah/botdiscord/src/plugins/onTick/authCheck.php:376
PHP  10. file_get_contents() /home/blah/botdiscord/src/lib/eveApi.php:156

Can upload the standing file if required.

Thoughts?

**Comment by shibdib** [comment]
ESI is being horribly inconsistent right now and ccp is aware of it. I'll look into adding a fallback for standings checks to old school api

**Comment by scopehs** [comment]
Damn that was quick.. i didn't even get my edit in!
