### ISSUE TITLE
Jabber Pings to Discord Not Working

### ISSUE THREAD

**Issue by djyumene** [shibdib/Dramiel#178]
I am trying to get the jabber pings section to work, and followed the guide step by step tho after getting everything set up, it will not broadcast pings to discord. 

There isn't any log really on this either.  When a ping goes through, I checked the logs and there's nothing in them to give anything in detail on what happened. 

 'fileReader' => array(
        'db' => '/tmp/discord.db',
        'channelConfig' => array(
            'pings' => array(
                'default' => true,
                'searchString' => 'broadcast', // The plugin will search for this string and post any messages that contain it. To have the bot shar$
                'textStringPrepend' => '@everyone |', // this prepend will ping all discord users with access to the channel
                'textStringAppend' => '', // anything ud like to add to the tail end of the bots message
                'channelID' => '##chanid##' // channel it posts too
            ),
            'supers' => array(
                'default' => false,
                'searchString' => 'supers',
                'textStringPrepend' => '@everyone |',
                'textStringAppend' => '',
                'channelID' => 0
            ),
            'blackops' => array(
                'default' => false,
                'searchString' => 'blops',
                'textStringPrepend' => '@everyone |',
                'textStringAppend' => '',
                'channelID' => 0
            )
        ),
    ),

**Comment by shibdib** [comment]
Ask around in discord ull get better help
