### ISSUE TITLE
Dramiel.ERROR: exception 'React\Dns\Query\TimeoutException'

### ISSUE THREAD

**Issue by Isoterik** [shibdib/Dramiel#181]
running two instances of the bot. the 2nd one keeps crashing with that error below. 
plugins in use are: evemails, notifications, siphons, siloFull

`[2017-01-08 21:28:00] Dramiel.ERROR: exception 'React\Dns\Query\TimeoutException' with message 'DNS query for gateway.discord.gg timed out' in /home/dramiel/outlow/Dramiel/vendor/react/dns/src/Query/Executor.php:69 Stack trace: #0 [internal function]: React\Dns\Query\Executor->React\Dns\Query\{closure}(Object(React\EventLoop\Timer\Timer)) #1 /home/dramiel/outlow/Dramiel/vendor/react/event-loop/src/Timer/Timers.php(90): call_user_func(Object(Closure), Object(React\EventLoop\Timer\Timer)) #2 /home/dramiel/outlow/Dramiel/vendor/react/event-loop/src/StreamSelectLoop.php(177): React\EventLoop\Timer\Timers->tick() #3 /home/dramiel/outlow/Dramiel/vendor/team-reflex/discord-php/src/Discord/Discord.php(1231): React\EventLoop\StreamSelectLoop->run() #4 /home/dramiel/outlow/Dramiel/Dramiel.php(296): Discord\Discord->run() #5 {main}  Next exception 'RuntimeException' with message 'DNS query for gateway.discord.gg failed: too many retries' in /home/dramiel/outlow/Dramiel/vendor/react/dns/src/Query/RetryExecutor.php:31 Stack trace: #0 /home/dramiel/outlow/Dramiel/vendor/react/promise/src/RejectedPromise.php(25): React\Dns\Query\RetryExecutor->React\Dns\Query\{closure}(Object(React\Dns\Query\TimeoutException)) #1 /home/dramiel/outlow/Dramiel/vendor/react/promise/src/Promise.php(119): React\Promise\RejectedPromise->then(NULL, Object(Closure)) #2 /home/dramiel/outlow/Dramiel/vendor/react/promise/src/Promise.php(174): React\Promise\Promise->React\Promise\{closure}(Object(React\Promise\RejectedPromise)) #3 /home/dramiel/outlow/Dramiel/vendor/react/promise/src/Promise.php(142): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise)) #4 /home/dramiel/outlow/Dramiel/vendor/react/promise/src/Promise.php(195): React\Promise\Promise->reject(Object(React\Dns\Query\TimeoutException)) #5 [internal function]: React\Promise\Promise->React\Promise\{closure}(Object(React\Dns\Query\TimeoutException)) #6 /home/dramiel/outlow/Dramiel/vendor/react/promise/src/Deferred.php(42): call_user_func(Object(Closure), Object(React\Dns\Query\TimeoutException)) #7 /home/dramiel/outlow/Dramiel/vendor/react/dns/src/Query/Executor.php(69): React\Promise\Deferred->reject(Object(React\Dns\Query\TimeoutException)) #8 [internal function]: React\Dns\Query\Executor->React\Dns\Query\{closure}(Object(React\EventLoop\Timer\Timer)) #9 /home/dramiel/outlow/Dramiel/vendor/react/event-loop/src/Timer/Timers.php(90): call_user_func(Object(Closure), Object(React\EventLoop\Timer\Timer)) #10 /home/dramiel/outlow/Dramiel/vendor/react/event-loop/src/StreamSelectLoop.php(177): React\EventLoop\Timer\Timers->tick() #11 /home/dramiel/outlow/Dramiel/vendor/team-reflex/discord-php/src/Discord/Discord.php(1231): React\EventLoop\StreamSelectLoop->run() #12 /home/dramiel/outlow/Dramiel/Dramiel.php(296): Discord\Discord->run() #13 {main} [] []`

**update:** happens every 20 to 30 minutes.
`[2017-01-09 19:02:57] DiscordPHP.INFO: gateway retrieved and set {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json"} []
[2017-01-09 19:02:57] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json"} []
[2017-01-09 19:02:58] DiscordPHP.INFO: websocket connection has been created [] []
[2017-01-09 19:02:58] DiscordPHP.INFO: received hello [] []
[2017-01-09 19:02:58] DiscordPHP.INFO: identifying {"payload":{"op":2,"d":{"token":"removed","properties":{"$os":"Linux","$browser":"DiscordPHP/v4.0.3 DiscordBot (https://github.com/teamreflex/DiscordPHP, v4.0.3)","$device":"DiscordPHP/v4.0.3 DiscordBot (https://github.com/teamreflex/DiscordPHP, v4.0.3)","$referrer":"https://github.com/teamreflex/DiscordPHP","$referring_domain":"https://github.com/teamreflex/DiscordPHP"},"compress":true}}} []
[2017-01-09 19:02:58] DiscordPHP.INFO: heartbeat timer initilized {"interval":41250} []
[2017-01-09 19:02:58] DiscordPHP.INFO: did not parse private channels [] []
[2017-01-09 19:02:58] DiscordPHP.INFO: stored guilds {"count":0} []
[2017-01-09 19:02:58] DiscordPHP.INFO: all guilds are now available {"count":1} []
[2017-01-09 19:02:58] DiscordPHP.INFO: loadAllMembers option is disabled, not setting chunking up [] []
[2017-01-09 19:02:58] DiscordPHP.INFO: client is ready [] []
[2017-01-09 19:03:56] DiscordPHP.WARNING: websocket closed {"op":1000,"reason":""} []
[2017-01-09 19:03:56] DiscordPHP.INFO: starting reconnect {"reconnect_count":1} []
[2017-01-09 19:03:56] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json"} []
[2017-01-09 19:04:37] DiscordPHP.ERROR: websocket error {"e":"DNS query for gateway.discord.gg failed: too many retries"} []`

**Comment by CokkocZateki** [comment]
RuntimeException' with message 'DNS query for gateway.discord.gg failed:
too many retries' in /home/dramiel/outlow/Dramiel

Where is the location of the bots?

**Comment by Isoterik** [comment]
> Where is the location of the bots?

may define the question a bit clearer? 

the bots share one user with an own folder each.

**Comment by CokkocZateki** [comment]
Sorry il try be a bit clearer. It seems like  discord gets flooded with the
traceback you posted. I'm not entirely sure but each bot is using its own
supervisor conf file right?

**Comment by Isoterik** [comment]
> Sorry il try be a bit clearer. It seems like discord gets flooded with the traceback you posted. I'm not entirely sure but each bot is using its own supervisor conf file right?

i am not able to use supervisor atm due it is unable to open the Dramiel.php file:
`Could not open input file: /home/dramiel/outlow/Dramiel.php` 
if i could use it, they have their own config for supervisor. 
i am running the bots atm with screen to test them.

**Comment by CokkocZateki** [comment]
The plot thickens.If you not already join the official Dramiel discord
server and we can chat there and debug your issue.

Incase you don't have the invite

https://discord.gg/wD7n6pr

**Comment by Isoterik** [comment]
> Incase you don't have the invite

joined

**Comment by Isoterik** [comment]
updated 1st post with new log from supervisor

**Comment by shibdib** [comment]
IMO sounds like a connection issue. Is this self hosted or are u using a professionally hosted server

**Comment by Isoterik** [comment]
> IMO sounds like a connection issue. Is this self hosted or are u using a professionally hosted server

root server at a data center

**Comment by shibdib** [comment]
hmm, not sure tbh. Network issues is not really my forte. I'm running 10 bots on one server right now with almost no issues. Hop on discord and ask around for help, not much I can do for u unfortunately.

**Comment by kassmed** [comment]
I have the same error. Tried on multiple servers without success. 

Here is a picture of a fresh install and run:
https://gyazo.com/73692ec4c5486e7f3b927802b227bbba

**Comment by shibdib** [comment]
https://github.com/teamreflex/DiscordPHP/issues/151#issuecomment-276548053
