### ISSUE TITLE
Error On Return from SSO

### ISSUE THREAD

**Issue by radioastro** [shibdib/Dramiel#183]
Bot is operational and responds to some of the !commands in our discord server.

Bot will not respond to !pc or !char, unless I put something in !pc that is definitely not an in game item, then it responds with a not found message.

Auth screen loads fine, goes to CCP, comes back to server, and the following error occurs:

Fatal error: Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/auth/app.php:45 Stack trace: #0 [internal function]: {closure}() #1 /var/www/auth/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array) #2 /var/www/auth/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch() #3 /var/www/auth/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call() #4 /var/www/auth/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call() #5 /var/www/auth/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php(87): Slim\Middleware\MethodOverride->call() #6 /var/www/auth/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware->call() #7 /var/www/auth/vendor/slim/slim/Slim/Slim.php(1300): Slim\Middleware\PrettyExceptions->call() #8 /var/www/auth/app.php(91): Slim\Slim->run() #9 /var/www/auth/public/index.php(3): require_once('/var/www/auth/a...') #10 {main} thrown in /var/www/auth/app.php on line 45

Any suggestions would be greatly appreciated.

**Comment by Isoterik** [comment]
got the php-xml extension for your php version installed?
e.g. `sudo apt-get install php5.6-xml`
seems like you are missing it.

**Comment by shibdib** [comment]
this is not an issue with the bot, jump in the discord for help
