### ISSUE TITLE
Feature Request: Blue standing for Auth members

### ISSUE THREAD

**Issue by CokkocZateki** [shibdib/Dramiel#186]
Hi
The blue standing for auth members doesn't work as expected.  

No permissions is assigned to blue who authed.

Outcome:
+5 +10 should be able to be assigned a group when using the auth function.

**Comment by scopehs** [comment]
Members that auth of standings are being assigned the 0 / neutral role, when the standing state they are 10.

**Comment by shibdib** [comment]
https://github.com/shibdib/Dramiel/commit/19c8c8221482465d437ccc37fab1faad1710d799

**Comment by CokkocZateki** [comment]
@shibdib function still doenst work for me. members getting kicked :(
