### ISSUE TITLE
Auth Errors

### ISSUE THREAD

**Issue by scopehs** [shibdib/Dramiel#190]
PHP Warning:  Invalid argument supplied for foreach() in /home/scopeh/phoenixbot/src/lib/eveApi.php on line 108
PHP Stack trace:
PHP   1. {main}() /home/scopeh/phoenixbot/Dramiel.php:0
PHP   2. Discord\Discord->run() /home/scopeh/phoenixbot/Dramiel.php:296
PHP   3. React\EventLoop\StreamSelectLoop->run() /home/scopeh/phoenixbot/vendor/team-reflex/discord-php/src/Discord/Discord.php:1246
PHP   4. React\EventLoop\StreamSelectLoop->waitForStreamActivity() /home/scopeh/phoenixbot/vendor/react/event-loop/src/StreamSelectLoop.php:201
PHP   5. call_user_func:{/home/scopeh/phoenixbot/vendor/react/event-loop/src/StreamSelectLoop.php:232}() /home/scopeh/phoenixbot/vendor/react/event-loop/src/StreamSelectLoop.php:232
PHP   6. React\Stream\Stream->handleData() /home/scopeh/phoenixbot/vendor/react/event-loop/src/StreamSelectLoop.php:232
PHP   7. Evenement\EventEmitter->emit() /home/scopeh/phoenixbot/vendor/react/stream/src/Stream.php:173
PHP   8. call_user_func_array:{/home/scopeh/phoenixbot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64}() /home/scopeh/phoenixbot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
PHP   9. Ratchet\RFC6455\Messaging\MessageBuffer->onData() /home/scopeh/phoenixbot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
PHP  10. Ratchet\RFC6455\Messaging\MessageBuffer->processData() /home/scopeh/phoenixbot/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php:60
PHP  11. Ratchet\Client\WebSocket->Ratchet\Client\{closure}() /home/scopeh/phoenixbot/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php:104
PHP  12. Ratchet\Client\WebSocket->emit() /home/scopeh/phoenixbot/vendor/ratchet/pawl/src/WebSocket.php:71
PHP  13. call_user_func_array:{/home/scopeh/phoenixbot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64}() /home/scopeh/phoenixbot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
PHP  14. Discord\Discord->handleWsMessage() /home/scopeh/phoenixbot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
PHP  15. Discord\Discord->handleDispatch() /home/scopeh/phoenixbot/vendor/team-reflex/discord-php/src/Discord/Discord.php:564
PHP  16. Discord\WebSockets\Events\MessageCreate->handle() /home/scopeh/phoenixbot/vendor/team-reflex/discord-php/src/Discord/Discord.php:690
PHP  17. React\Promise\Deferred->resolve() /home/scopeh/phoenixbot/vendor/team-reflex/discord-php/src/Discord/WebSockets/Events/MessageCreate.php:38
PHP  18. call_user_func:{/home/scopeh/phoenixbot/vendor/react/promise/src/Deferred.php:35}() /home/scopeh/phoenixbot/vendor/react/promise/src/Deferred.php:35
PHP  19. React\Promise\Promise->React\Promise\{closure}() /home/scopeh/phoenixbot/vendor/react/promise/src/Deferred.php:35
PHP  20. React\Promise\Promise->resolve() /home/scopeh/phoenixbot/vendor/react/promise/src/Promise.php:192
PHP  21. React\Promise\Promise->settle() /home/scopeh/phoenixbot/vendor/react/promise/src/Promise.php:133
PHP  22. React\Promise\Promise->React\Promise\{closure}() /home/scopeh/phoenixbot/vendor/react/promise/src/Promise.php:174
PHP  23. React\Promise\FulfilledPromise->then() /home/scopeh/phoenixbot/vendor/react/promise/src/Promise.php:119
PHP  24. Discord\Discord->Discord\{closure}() /home/scopeh/phoenixbot/vendor/react/promise/src/FulfilledPromise.php:25
PHP  25. Discord\Discord->emit() /home/scopeh/phoenixbot/vendor/team-reflex/discord-php/src/Discord/Discord.php:666
PHP  26. call_user_func_array:{/home/scopeh/phoenixbot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64}() /home/scopeh/phoenixbot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
PHP  27. {closure:/home/scopeh/phoenixbot/Dramiel.php:243-274}() 
/home/scopeh/phoenixbot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
PHP  28. auth->onMessage() /home/scopeh/phoenixbot/Dramiel.php:267
PHP  29. characterName() /home/scopeh/phoenixbot/src/plugins/onMessage/auth.php:148

Also from libaryError.log

scopeh@localhost:~/phoenixbot/log$ cat libraryError.log
[2017-01-26 11:35:55] eveApi.ERROR: EVE API Error: String could not be parsed as XML [] []

Issues include, remoe users roles, naming conventions not working.

Etc.

**Comment by shibdib** [comment]
Auth is working fine for me? Anyone else having issues?

**Comment by CokkocZateki** [comment]
working fine for me

**Comment by shibdib** [comment]
Looks like an api hiccup and then the lib messing up. Shouldn't effect auth long term. 

A lot of the errors don't need to be acted on, they're more there for me to know what needs to be cleaned up.
