### ISSUE TITLE
type ## unmapped master issue...

### ISSUE THREAD

**Issue by shibdib** [shibdib/Dramiel#191]
Report any notifications that give you the "unmapped" error here. 

Please include the full text, and what the notification actually is ingame.

**Comment by CokkocZateki** [comment]
Hi @shibdib 
i got one

From: DED
Sent: 2017.01.27 11:30

This notification is to advise you that there are not enough fuel blocks present to support one full day of service module activity

Types and quantities present:
208x Nitrogen Fuel Block


typeID 181 is an unmapped notification, please create a Github issue with this entire message and please include what the in-game notification is.

**Comment by shibdib** [comment]
181 was already added https://github.com/shibdib/Dramiel/commit/1d7ecec074307d011b44561b0f93546c343543a7

make sure u do a pull

**Comment by CokkocZateki** [comment]
hmm interesting. i done the pull yesterday before we got that notification. il check it out

**Comment by CokkocZateki** [comment]
hi again. so this isnt really unmapped but seems like an old issue thats came up on my server.

Alliance/Corp joining war isnt shown on the ping

@everyone | War declared by  against . Fighting begins in roughly 24 hours.

The war between  and  has been joined by a third party. This new group may begin fighting in roughly 24 hours.

**Comment by CokkocZateki** [comment]
and i got another one :(

typeID 123 is an unmapped notification, please create a Github issue with this entire message and please include what the in-game notification is.

Fubar INC surrenders to Wrecking Machine.
From: CONCORD
Sent: 2017.01.28 10:20

The war between Fubar INC and Wrecking Machine. is coming to an end. Fubar INC has surrendered to Wrecking Machine.. The war will be declared as being over after approximately 24 hours and Wrecking Machine. will be unable to declare war on Fubar INC for the next 2 weeks.

**Comment by shibdib** [comment]
Need the xml version of that notification to do anything with it

**Comment by Husteln** [comment]
typeID 36 is an unmapped notification, please create a Github issue with this entire message and please include what the in-game notification is. endDate: 131365792080000000 ownerID: 1889867089 reason: 1 shipID: 1023244996648 startDate: 131293216080000000 typeID: 16227

row notificationID="615548003" typeID="36" senderID="1000132" senderName="Secure Commerce Commission" sentDate="2017-02-24 19:36:00" read="1"

**Comment by ZafirG** [comment]
typeID 25 is an unmapped notification, please create a Github issue with this entire message and please include what the in-game notification is. body: 'Located at:: ****** VI - ****** 23 - Federation Navy Testing Facilities    Material Efficiency: 10    Time Efficiency: 20' subject: Unlock the Mining Laser Optimization Charge Blueprint

Mail Body### 
Corporate Vote - Unlock the Mining Laser Optimization Charge Blueprint
From: ******
Sent: 2017.03.05 06:04

Located at:: ***** VI - ****** 23 - Federation Navy Testing Facilities
Material Efficiency: 10
Time Efficiency: 20

**Comment by Valleriani** [comment]
typeID 146 is an unmapped notification, please create a Github issue with this entire message and please include what the in-game notification is. corpID: 98101105

I don't exactly know what the message is here. The last message in our corporation activity log for today is:

Corporation friendly-fire is now an illegal act
From: TriFlexure
Sent: 2017.03.22 08:45

The ‘friendly-fire’ aggression policy within TriFlexure has now changed. Aggressive actions between corporation members are now considered an illegal action, subject to standard CONCORD penalty protocols.
Corporation members will now receive Criminal or Suspect flags for attacking others in Empire-controlled space.

which could be it.

**Comment by thorynatech** [comment]
> typeID 29 is an unmapped notification, please create a Github issue with this entire message and please include what the in-game notification is. againstID: (corp1id) cost: null declaredByID:(corp2id)

The war between (corp1) and (corp2) is coming to an end. (corp1) has surrendered to (corp2). The war will be declared as being over after approximately 24 hours and (corp2) will be unable to declare war on (corp1) for the next 2 weeks.

**Comment by CokkocZateki** [comment]
got another one here. missing alliances names

`The war between  and  has been invalidated. Fighting ends in roughly 24 hours.`

```
ingame message

CONCORD invalidates war declared by Wrecking Machine. against Hammer Securities

From: CONCORD

Sent: 2017.04.04 19:37



CONCORD has declared this war invalid as it breaches one or more articles in the Yulai Convention. The war will be declared as being over after approximately 24 hours.
```

**Comment by CokkocZateki** [comment]
got another one here @shibdib 

```
POS in  - Unknown needs fuel. Only  's remaining.



ingame notification: 

Report: Starbase low on resources in J10**OPSEC**
From: DED
Sent: 2017.04.13 14:00


This notification is to advise you that there are not enough resources present to last a day of full Starbase activity.
```

**Comment by westonmyers** [comment]
@shibdib Another one

```
typeID 22 is an unmapped notification, please create a Github issue with this entire message and please include what the in-game notification is. corpID: 98493749 newCeoID: 868675347 oldCeoID: 1128616906
```
```
Lucia Tarjin is the new CEO of Atlas Holdings.
From: AndyHasRoids
Sent: 2017.05.09 19:08

AndyHasRoids has resigned from the position of CEO with Atlas Holdings.. As their last move they appointed Lucia Tarjin as CEO.
```

**Comment by CokkocZateki** [comment]
@shibdib my wardec info is still the same
`The war between and has been invalidated. Fighting ends in roughly 24 hours.`

**Comment by HunHawk** [comment]
ESS contribution was stolen:
``typeID 134 is an unmapped notification, please create a Github issue with this entire message and please include what the in-game notification is. charID: 149517312 myIsk: 236829.75 totalIsk: 82662035.88``

**Comment by HunHawk** [comment]
Clone state omega time added to account:
```typeID 1032 is an unmapped notification, please create a Github issue with this entire message and please include what the in-game notification is. {}```
Nothing else happened all day.

**Comment by shibdib** [comment]
Housekeeping
