### ISSUE TITLE
dramiel not posting killmails at all.

### ISSUE THREAD

**Issue by warriorsoul15** [shibdib/Dramiel#195]
It isnt throwing anything in the logs other than there are no new killmails even when i set the value back a few days worth of killmails.

I looked at zKill.php and I no longer see the killmail parsing code in there did it get moved somewhere?

**Comment by ZafirG** [comment]
it seems that bigkills channel are posting, however configured corp and alliance are not. may have to do with the zKill SSO authentication change. maybe access attributes may have changed.

**Comment by warriorsoul15** [comment]
if you copy the URL it works.

**Comment by Jimmy062006** [comment]
I'm testing a clean install on a new VM Ubuntu install. Time will tell :)

**Comment by WerzSoft** [comment]
Any updates on this? keeps failing to me too

**Comment by Jimmy062006** [comment]
It should work fine now with commit https://github.com/shibdib/Dramiel/commit/334f84190c252cd885f83d87b221241ee3acedac
