### ISSUE TITLE
Error running 

### ISSUE THREAD

**Issue by emrysalf** [shibdib/Dramiel#2]
Thank you for your dedication!!!

I seem to have run into a issue. I have some doubts as to my setting up config. 
supervisorctl restart dramiel  runs nicely. 

But when I try to talk to to the bot "!help" get nothing. Went to log error and below over and over. 

```
PHP Fatal error:  Call to a member function sendMessage() on a non-object in /var/www/html/src/plugins/onTick/periodicStatusCheck.php on line 122
PHP Notice:  Undefined index: guildID in /var/www/html/src/plugins/onMessage/auth.php on line 79
PHP Notice:  Undefined index: periodicCheck in /var/www/html/src/plugins/onTick/authCheck.php on line 107
```

Here are the parts of my config that I have changed. 

```
`"token" => "XxXxXxX0Xxx1MTExNjI5MzE0.XxXXxX.BdRCYqokTqTSGU1yU_gm0uUWutA"`
```

Have checked this 3 times.. This is from https://discordapp.com/developers/applications/me/
"My Applications" and the "APP BOT USER" and token below. 

```
    "user" => "xxxxxxxxxx",
    "pass" => "xxxxxxxxxx",
```

```
$config["eve"] = array(
    "apiKeys" => array(
        "user1" => array(
            "keyID" => "123456789",   
              "vCode" => "XXXX",   `    
```

(Main Char api "Char info+Standings)

`"characterID" => 1234`         (Char ID from Discord. Tried ID for char from zkill but no difference)

When I turn on the zkill by adding 
       `"allianceID" => 1234567,`            (Alliance iD I get from zkill did not add one for corp)

Error changes to 

```
PHP Fatal error:  Call to a member function sendMessage() on a non-object in /var/www/html/src/plugins/onTick/periodicStatusCheck.php on line 122
PHP Notice:  Undefined index: guildID in /var/www/html/src/plugins/onMessage/auth.php on line 79
PHP Notice:  Undefined index: periodicCheck in /var/www/html/src/plugins/onTick/authCheck.php on line 107
```

I have added the bot a few times. I did notice that it does not show up under "Authorised Applications".
`https://discordapp.com/oauth2/authorize?&client_id=xxx&scope=bot`
xxx = Client/Application ID from https://discordapp.com/developers/applications/me/

Did not set up auth  yet. 

Thank you!!

**Comment by shibdib** [comment]
You need to set a channel for the bot to report server downtimes. 

```
// what channel for eve notifications/also the channel for tq status alerts
"notifications" => array(
    "channelID" => 0
),
```

That will solve the issue. I'll add something right now to make sure the bot doesn't die if that isn't set

**Comment by shibdib** [comment]
it will now throw an error instead of killing the bot

`[2016-07-08 01:37:59] Dramiel.INFO: TQ Status Check Failed - Add a channel ID to the notifications section in the config. [] []`
