### ISSUE TITLE
Tweaking Fleetup interaction

### ISSUE THREAD

**Issue by warriorsoul15** [shibdib/Dramiel#20]
I have a few questions on tweaking.

FleetUp doesnt seem to post new operations when posted only upcoming ones.

What is the interval for "upcoming" to post and does it re-ping a few times? How can I modify this so say upcoming is 12hrs instead of 1 or whatever it is now.

---

What is the poller interval for notifications because I have a bot on Slack that seems to get notifications 5-6 minutes faster than this, is this adjustable? If so, where?
## 

Any plans for expansion into posting updated/new FleetUP doctrine/fitting changes? Or responding to a command to spit a link to a fitting?

**Comment by shibdib** [comment]
1. Fleetup right now checks every 30 minutes for new operations and every 2 minutes for upcoming (within 30 minutes). 
2. Notifications are based off the cache set by ccp. It's impossible for you to be getting anything faster as the bot checks as soon as the api updates.
3. I could, depends on the demand as I'm not sure how widely used the fleetup features are being used.

**Comment by CokkocZateki** [comment]
fleetup is widely used by alot of alliances. its the must have tool for medium-Large sizes corps/alliances
