### ISSUE TITLE
Add a !leave command

### ISSUE THREAD

**Issue by Bawbd** [shibdib/Dramiel#202]
Hello,

Would you add a command like !leave so the bot leaves the server?

Then people with admin permissions on the bot but not on the discord server can kick it.

Thanks in advance and keep up the good work.

**Comment by CokkocZateki** [comment]
could i ask why you want the bot to leave the server?

**Comment by Bawbd** [comment]
There are multiple reasons why any user would want the bot to leave the server and you can do it easily by kicking the bot if you have server permissions.

In my case, I'm self hosting multiple instances of the bot and I would like to allow some people to kick it if needed without giving them server permissions.

I'm using another bot called Red that has that command for example.

**Comment by shibdib** [comment]
I don't plan on writing this in as I think it's redundant when you can kick. But if a pull is made with it I'd add it.
