### ISSUE TITLE
Roles aren't being removed. Period.

### ISSUE THREAD

**Issue by Husteln** [shibdib/Dramiel#212]
* **Problem**: Roles aren't being removed from members. Doesn't matter what member or what role. Yes, bot's role is above others and he has the necessary permissions. Yes, it's adding them like it should. Yes, renaming is fine.
* **Expected**: I expected that members will always have correct roles, even if they want to re-auth every five minutes.
* **Logs / Screenshots / Proof**: Hosted version.
* **Version Info**: Hosted version.

**Comment by shibdib** [comment]
https://github.com/shibdib/Dramiel/commit/f1e6be3ccd8548940a2f0a35d759f0458c47d742
