### ISSUE TITLE
unable pull killmails due to variable

### ISSUE THREAD

**Issue by jagyro** [shibdib/Dramiel#226]
[dramielerror.log]

PHP Notice:  Undefined variable: killID in /home/dramiel/Dramiel/src/plugins/onTick/getKillmails.php on line 181
PHP Stack trace:
PHP   1. {main}() /home/dramiel/Dramiel/Dramiel.php:0
PHP   2. Discord\Discord->run() /home/dramiel/Dramiel/Dramiel.php:311
PHP   3. React\EventLoop\StreamSelectLoop->run() /home/dramiel/Dramiel/vendor/team-reflex/discord-php/src/Discord/Discord.php:1249
PHP   4. React\EventLoop\Timer\Timers->tick() /home/dramiel/Dramiel/vendor/react/event-loop/src/StreamSelectLoop.php:177
PHP   5. call_user_func:{/home/dramiel/Dramiel/vendor/react/event-loop/src/Timer/Timers.php:90}() /home/dramiel/Dramiel/vendor/react/event-loop/src/Timer/Timers.php:90
PHP   6. {closure:/home/dramiel/Dramiel/Dramiel.php:179-183}() /home/dramiel/Dramiel/vendor/react/event-loop/src/Timer/Timers.php:90
PHP   7. getKillmails->tick() /home/dramiel/Dramiel/Dramiel.php:181
PHP   8. getKillmails->getKM() /home/dramiel/Dramiel/src/plugins/onTick/getKillmails.php:74

**Comment by rynan7** [comment]
I have the same issue, have you heard anything about it yet?
