### ISSUE TITLE
twisted.out.log write delay

### ISSUE THREAD

**Issue by homebrewhops** [shibdib/Dramiel#227]
* **Problem**: After starting twisted with an xmpp config, tailing twisted.out.log shows that logging stops abruptly, ~~then there is a long delay of 5min then logging continues~~. logged messages are cutoff and no longer continue.
* **Expected**: Once twisted is started and connected to xmpp, logging should not delay

tail-f /var/dramiel/log/twisted.out.log
```
12:59:42 Pong: <iq xmlns='jabber:client' to='xmpp.local' type='result' id='830-2405345'/>
13:02:12 Got a ping: <iq xmlns='jabber:client' from='xmpp.local' type='get' id='443-2405480' to='jack@xmpp.local/b2mt67tnra'><ping xmlns='urn:xmpp:ping'/></iq>
13:02:12 Pong: <iq xmlns='jabber:client' to='xmpp.local' type='result' id='443-2405480'/>
13:04:43 Got a ping: <iq xmlns='jabber:client' from='xmpp.local' type='get' id='73-2405633' to='jack@xmpp.local/b2mt67tnra'><ping xmlns='urn:xmpp:ping'/></iq>
13:04:43 Pong: <iq xmlns='jabber:client' to='xmpp.local' type='result' id='73-2405633'/>
13:07:13 Got a ping: <iq xmlns='jabber:client' from='xmpp.local' type='get' id='423-2405784' to='jack@xmpp.local/b2mt67tnra'><ping xmlns='urn:xmpp:p
```
The log file is cut off at <ping xmlns='urn:xmpp:p

The twisted bot appears to be functioning correctly except for logging.

**Comment by shibdib** [comment]
Not sure this is something I can fix as I'm not the twisted dev
