### ISSUE TITLE
All but zkill

### ISSUE THREAD

**Issue by IronWarjack** [shibdib/Dramiel#233]
This is a new install last week, it is up and running and all plugins that I set enabled are working minus grabbing zkillboard info.

No errors in dramielError.log, the plugin is uncommentated, and I've checked and rechecked my discord channels, zkillboard ids and what not.

The only thing I do see is a lot of "[2017-06-22 14:47:50] Db.ERROR: could not find driver [] []" in libraryError.log which is a bit ambiguous.

I followed your Install directions generally to a T.

Ubuntu 14.04.1
PHP 5.6.30

Thanks for any suggestions
Lars

**Comment by BroodLK** [comment]
We have a Discord channel for support. 
https://discord.gg/wD7n6pr

Also you didn't install SQlite, or there is an issue with your install of SQlite.
Also, I know the instructions say use php5, however you need to use php7.

**Comment by IronWarjack** [comment]
Ug, OK.  I am not 1000% sure if the other things I have on my server will allow me to move to 7.0 so I'll look into that.  I did verify sqlite3 is installed and working (and enabled for PHP 5.6).

**Comment by IronWarjack** [comment]
Closing, LTR (learn to read) is key here.  I totally mistook the proper sqlite version, and caused my issue.
