### ISSUE TITLE
A divider between evemail messages

### ISSUE THREAD

**Issue by IronWarjack** [shibdib/Dramiel#234]
Small feature request.

When the evemail fires off, if more than one message is sent too close, it jumbles them together, making it hard to see there were two messages end and begin.

![image](https://user-images.githubusercontent.com/9136122/27499432-d02c3cae-5831-11e7-830e-43f6a1545785.png)

Anyway to add a spacer or a divider line to help the visual of message dividers?

**Comment by scragly** [comment]
File: /src/plugins/onTick/evemails.php
Line: 162
Adding in a line before the Mail By section will allow it act as a divider. 

Looks like shibdib already got it sorted though.
