### ISSUE TITLE
zKillboard API changed

### ISSUE THREAD

**Issue by HunHawk** [shibdib/Dramiel#237]
zKillboard changed their API, and now the bot can't post killmails. Can you upgrade the bot or it's discontinued?

**Comment by HunHawk** [comment]
I updated the bot to latest commits, but killmail report still not working, and nothing in error logs. The !char command is not working too. It says "Error: ZKill is down. Try again later."

**Comment by shibdib** [comment]
this is apparently not fixed yet -_-

**Comment by Maulth** [comment]
Any idea when this might get fixed? I tried to do a bit of a change similar to what Allianceauth did https://github.com/allianceauth/allianceauth/commit/313cac6ac78e2a130541126412524f3276a917f6 but it didn't really work. RedisQ doesn't seem to have been updated for the Zkill API changes either.

**Comment by Noobforlife** [comment]
Got the same issue. zkillboard stopped working @shibdib are u working on a fix sir?

**Comment by shibdib** [comment]
I am
