### ISSUE TITLE
Feature Request: Better Broadcasts

### ISSUE THREAD

**Issue by CokkocZateki** [shibdib/Dramiel#28]
Hi.

currently when a war is declared or declared invalid a broadcast is sent saying `New war declared by.`

It doesnt give the name of the group declaring the war.

**Comment by shibdib** [comment]
http://i.imgur.com/EH3gHLo.png

?

Have you done a git pull (and composer update) lately?

**Comment by CokkocZateki** [comment]
Strange. Mine always repacked the corp/alliance name with a .

**Comment by shibdib** [comment]
I know it was an issue but it should have been fixed with https://github.com/shibdib/Dramiel/commit/db90b20fdc8778fbbc2889d6397d024b830abf75

**Comment by CokkocZateki** [comment]
ok i will update to the latest Version tonight then. any idea on #14 if its possible @shibdib ?
