### ISSUE TITLE
PHP Warning: filesize(): stat failed

### ISSUE THREAD

**Issue by jagyro** [shibdib/Dramiel#32]
PHP Warning:  filesize(): stat failed for /home/Dramiel/src/lib/../../database/ccpData.sqlite in /home/Dramiel/src/lib/updateCCPData.php on line 37
PHP Warning:  fopen(https://www.fuzzwork.co.uk/dump/sqlite-latest.sqlite.bz2): failed to open stream: Connection timed out in /home/Dramiel/src/lib/cURL.php on line 76
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: mapSolarSystems' in /home/Dramiel/src/lib/Db.php:128
Stack trace:
#0 /home/Dramiel/src/lib/Db.php(128): PDO->prepare('SELECT solarSys...')
#1 /home/Dramiel/src/plugins/onMessage/price.php(66): dbQuery('SELECT solarSys...', Array, 'ccp')
#2 /home/Dramiel/Dramiel.php(116): price->init(Array, Object(Discord\Discord), Object(Monolog\Logger))
#3 {main}

  thrown in /home/Dramiel/src/lib/Db.php on line 128
PHP Warning:  fopen(https://www.fuzzwork.co.uk/dump/sqlite-latest.sqlite.bz2): failed to open stream: Connection timed out in /home/Dramiel/src/lib/cURL.php on line 76
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: mapSolarSystems' in /home/Dramiel/src/lib/Db.php:128
Stack trace:
#0 /home/Dramiel/src/lib/Db.php(128): PDO->prepare('SELECT solarSys...')
#1 /home/Dramiel/src/plugins/onMessage/price.php(66): dbQuery('SELECT solarSys...', Array, 'ccp')
#2 /home/Dramiel/Dramiel.php(116): price->init(Array, Object(Discord\Discord), Object(Monolog\Logger))
#3 {main}

  thrown in /home/Dramiel/src/lib/Db.php on line 128

not sure what to do about this

**Comment by jagyro** [comment]
I've pinged fuzzwork and it just sits there.  Happen to know if it is a port issue?

**Comment by shibdib** [comment]
Not able to duplicate this, deleted my ccpdata database and it correctly used filesize() to determine it was too small and redownloaded from fuzzworks just fine.
