### ISSUE TITLE
pricecheck lets the bot die

### ISSUE THREAD

**Issue by Maxcraft90** [shibdib/Dramiel#33]
hey

i updated the bot to the newest version, but somehow, if I start for example !jita Paladin the bot will die and be restarted.

**Comment by Maxcraft90** [comment]
Ok correction: It can also happen if other commands come up. I don't know where to look, the error Logfile doesn't show anything useful.

**Comment by shibdib** [comment]
Not able to reproduce it (every once in awhile get an xml error but that's ccp issues). Can you double check the logs?

And also check your servers memory usage and let me know how much free memory you have.

**Comment by Maxcraft90** [comment]
i have more than 3.5GB mem available
it's a bit strange, that the pluginloading is running every like 10 seconds:

> [2016-09-11 21:17:44] Dramiel.INFO: Checking authed users for changes.... [] []
> [2016-09-11 21:17:45] Dramiel.INFO: Logger Initiated [] []
> [2016-09-11 21:17:45] Dramiel.INFO: CCP Database already up to date [] []
> [2016-09-11 21:17:45] Dramiel.INFO: Loading background plugins [] []
> [2016-09-11 21:17:45] Dramiel.INFO: Loaded: 3 background plugins [] []
> [2016-09-11 21:17:45] Dramiel.INFO: Loading in chat plugins [] []
> [2016-09-11 21:17:45] Dramiel.INFO: Loaded: 10 chat plugins [] []
> [2016-09-11 21:17:46] Dramiel.INFO: Discord WebSocket is ready!  [] []
> [2016-09-11 21:17:51] Dramiel.INFO: Checking authed users for changes.... [] []
> [2016-09-11 21:17:52] Dramiel.INFO: Logger Initiated [] []
> [2016-09-11 21:17:52] Dramiel.INFO: CCP Database already up to date [] []
> [2016-09-11 21:17:52] Dramiel.INFO: Loading background plugins [] []
> [2016-09-11 21:17:52] Dramiel.INFO: Loaded: 3 background plugins [] []
> [2016-09-11 21:17:52] Dramiel.INFO: Loading in chat plugins [] []
> [2016-09-11 21:17:52] Dramiel.INFO: Loaded: 10 chat plugins [] []
> [2016-09-11 21:17:53] Dramiel.INFO: Discord WebSocket is ready!  [] []
> [2016-09-11 21:17:58] Dramiel.INFO: Checking authed users for changes.... [] []
> [2016-09-11 21:17:59] Dramiel.INFO: Logger Initiated [] 

should this be normal?

ErrorLog just shows me some failures in the authCheck.php but that's since I have no guild ID set:

> PHP Fatal error:  Call to a member function get() on null in /var/discord/Dramiel/src/plugins/onTick/authCheck.php on line 160
> PHP Notice:  Trying to get property of non-object in /var/discord/Dramiel/src/plugins/onTick/authCheck.php on line 125
> PHP Warning:  Invalid argument supplied for foreach() in /var/discord/Dramiel/src/plugins/onTick/authCheck.php on line 125
> PHP Notice:  Trying to get property of non-object in /var/discord/Dramiel/src/plugins/onTick/authCheck.php on line 160
> PHP Fatal error:  Call to a member function get() on null in /var/discord/Dramiel/src/plugins/onTick/authCheck.php on line 160
> PHP Notice:  Trying to get property of non-object in /var/discord/Dramiel/src/plugins/onTick/authCheck.php on line 125
> PHP Warning:  Invalid argument supplied for foreach() in /var/discord/Dramiel/src/plugins/onTick/authCheck.php on line 125
> PHP Notice:  Trying to get property of non-object in /var/discord/Dramiel/src/plugins/onTick/authCheck.php on line 160
> PHP Fatal error:  Call to a member function get() on null in /var/discord/Dramiel/src/plugins/onTick/authCheck.php on line 160
> PHP Notice:  Trying to get property of non-object in /var/discord/Dramiel/src/plugins/onTick/authCheck.php on line 125
> PHP Warning:  Invalid argument supplied for foreach() in /var/discord/Dramiel/src/plugins/onTick/authCheck.php on line 125
> PHP Notice:  Trying to get property of non-object in /var/discord/Dramiel/src/plugins/onTick/authCheck.php on line 160
> PHP Fatal error:  Call to a member function get() on null in /var/discord/Dramiel/src/plugins/onTick/authCheck.php on line 160

the "OtherLog" also did not show any suspicious behaviour...

just did another pull and update, after restarting the bot i tried again with !about. 2 times it worked, third time killed him and he restarted again.

After watching a bit closer I came to the conclusion that it's not the command. The bot is being restarted every few seconds. I don't know if discord kicks him or whatever happens...

**Comment by shibdib** [comment]
The issue is 

PHP Fatal error: Call to a member function get() on null in /var/discord/Dramiel/src/plugins/onTick/authCheck.php on line 160

fatal errors = a bot crash. I'll look into it and push out a fix, gimme a few minutes

**Comment by shibdib** [comment]
It shouldn't crash if you do a pull now.. BUT it will probably throw an error in the log now. I'm guessing you have the wrong guildID in your config.. The first section of the config where it says guild, you need to put the ID of your guild (server) there.

**Comment by Maxcraft90** [comment]
works like a charm now, thx a lot
