### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by scopehs** [shibdib/Dramiel#38]
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 26 file is encrypted or is not a database'

Has anyone came across this, Error Log is spewing it and bot is not coming online.
- ta

**Comment by shibdib** [comment]
Mmmm this is a new one to me. Try updating to the latest version, if it's the ccp database than that will fix it.

**Comment by scopehs** [comment]
shibdib, reset up, and i believe it is working correctly, i may have made a change in the config.php , as i left this one as default. i'll keep you posted. thanks
