### ISSUE TITLE
Bad auto update

### ISSUE THREAD

**Issue by fuzzysteve** [shibdib/Dramiel#40]
I run fuzzwork.co.uk, and every so often, I get someone downloading the database once per minute. This isn't a small amount of bandwidth, and is entirely unnecessary.

I'm seeing them download the md5, then download the database, at lease once per minute.

This leads to me banning the IP, which is less than ideal for everyone involved.

**Comment by shibdib** [comment]
New (updated in the past 2 months) versions have a catch to prevent this. I'll see about improving this but if people don't update there's not much I can do (And any ip bans are deserved in this case) 

Will look into moving away from a local db for lookups
