### ISSUE TITLE
iskvalue

### ISSUE THREAD

**Issue by jagyro** [shibdib/Dramiel#48]
I'm trying to figure a way to pull isk value of kill.  I the api zkill uses seems to have a /iskValue/#/ for it but I can't seem to figure a way to work.  Any help would be appreciated.

https://github.com/zKillboard/zKillboard/wiki/API-(Killmails)

https://zkillboard.com/api/xml/no-attackers/no-items/orderDirection/asc/afterKillID/{$lastMail}/allianceID/{$this->allianceID}/ is the address its pulling the kills from correct?  Cause when I manually add the address with the correct allianceID and any killmail# it goes to a blank page

**Comment by shibdib** [comment]
"iskValue will returns killmails that have a value equal to or greater than the value passed"

So it can be used to look for the "big" kills. But not as a way to get the value of the kill. You could page scrape the get the isk value, probably the only real option for it.

And yes that's correct, https://zkillboard.com/api/xml/no-attackers/no-items/orderDirection/asc/afterKillID/1000/allianceID/99005805/ works fine for me.

**Comment by Bingmano** [comment]
i think that stuff is stored in the stats portion of the API.

e.g from above: https://zkillboard.com/api/stats/allianceID/99005805/

**Comment by jagyro** [comment]
when you put in 1000, where is the bot getting that number??

**Comment by shibdib** [comment]
I just stuck that in there. That number is where the api will start as far
as mails go. So if you put 1 there it will pull every kill mail for the
corp/alliance

**Comment by Bingmano** [comment]
so i noticed that i did a pull and ISK value of kill was appearing, now after a second pull (latest version) ISK value no longer appears.

**Comment by shibdib** [comment]
http://i.imgur.com/qhjsEMx.png

it varies kill to kill, the link info is from zkill so it's an issue on their end that it isn't consistent. I'll look into adding a page scrape to get the info every time

**Comment by jagyro** [comment]
you can pull that info from https://zkillboard.com/api/kills/allianceID/<allianceID> which in there you can also pull alliance members involved on top of that.

**Comment by Bingmano** [comment]
ah ok that makes sense that the problem is coming from their end.  I use a slack bot as well that pulls this info and it never misses a value, https://github.com/VictorBersy/eve-online-killboard-to-slack.  it's written in ruby but it might give you some ideas.

**Comment by shibdib** [comment]
it's available in the json version of the api, just not the xml version. I'm not a huge fan of json so I put a request in that it also be added to the xml version. Once that's implemented it will be super easy for me to get added to the bot

**Comment by jagyro** [comment]
has there been any word on adding it to the xml?  

the json version has a bunch of info compaired to xml

**Comment by shibdib** [comment]
Nope (And I've been busy)

I may just switch it over to json -_-
