### ISSUE TITLE
Siphon Detection

### ISSUE THREAD

**Issue by scopehs** [shibdib/Dramiel#56]
Awesome idea, however if you are carrying out an unrefined reaction with a unit of 1, it will flag a siphon, as its not an inc of 100. Is there a possible fix for this?

**Comment by shibdib** [comment]
I can add checks for this, just need an example of what you're talking
about

**Comment by shibdib** [comment]
Commit 7d6c6bf fixes this for now. The bot now only checks raw goo silos, didn't even think about reactions when I wrote this.
