### ISSUE TITLE
Fleetup issues..

### ISSUE THREAD

**Issue by emrysalf** [shibdib/Dramiel#59]
Could just be bad config and reaching out for any advice folk might have..

In dramiel error logs I am getting 
`PHP Warning:  Invalid argument supplied for foreach() in /var/www/Dramiel/src/plugins/onTick/fleetUpOperations.php on line 103`

everything else seems to work great.. 
From settings file

```
    "fleetUpOperations", // integrate with fleet up and post any new operations and then ping them when they get close

    //Fleet up linking will share operations to a specific channel and then reping them when it gets within 30 minutes of form up
    "fleetUp" => array(
        "channelID" => 12345678901234567890, //We got from discord
        "userID" => 12345, //fleet up user id
        "groupID" => 12345, //fleet up group id
        "apiKey" => "LotsofLettersandNumbers", //fleet up api code, link to application Dramiel Bot
    ),
```

From http://fleet-up.com/Api/MyKeys
I get userID  and then API Code which I assume is "apiKey"

**Comment by CokkocZateki** [comment]
@emrysalf how did u fit your fleet up. im having the same issue
