### ISSUE TITLE
ESS contribution was shared notification

### ISSUE THREAD

**Issue by HunHawk** [shibdib/Dramiel#61]
Hi.
Bot says: 
typeID 135 is an unmapped notification, please create a Github issue with this entire message and please include what the in-game notification is. charID: 93100628 myIsk: 93246544.0 totalIsk: 2011363862.34

Ingame notification:
Nickolas Timmothy chose to share the value of the ESS pool. The pool was 2 011 363 862 ISK. Your share was 93 246 544 ISK.

**Comment by shibdib** [comment]
will fix in the next push

**Comment by HunHawk** [comment]
typeID 34 is getting a noobship, typeID 35 is insurance payout after ship loss

**Comment by HunHawk** [comment]
TypeID 135 is ESS share was stolen.

**Comment by shibdib** [comment]
135 should already be added
