### ISSUE TITLE
Alliance Auth

### ISSUE THREAD

**Issue by scopehs** [shibdib/Dramiel#62]
Would it be possible to have multiple alliances on the auth check?

Thanks

Thanks for adding the silo fix for reactions!

Good Job.

**Comment by shibdib** [comment]
like for a coalition discord? If you're in this alliance or this alliance or this.. etc...

**Comment by shibdib** [comment]
basic support added, still need to add the seperate roles for each group function

**Comment by scopehs** [comment]
Hey shib thanks dude, so multiple alliances I would use alliance id,alliance I'd,alliance I'd, etc in the config file under sso auth?  Thanks again scopeh

**Comment by shibdib** [comment]
disregard that, ended up purging roles -_- need to test it more before i push it out officially

**Comment by scopehs** [comment]
Heh np mate, good job with the bot so far , would be nice to have this to control coalition discord.
