### ISSUE TITLE
Request "Killmail" Multiple Alliances in different Channels 

### ISSUE THREAD

**Issue by shoyumimura** [shibdib/Dramiel#63]
Corp and Alliance Killmails in one Channel is Working good. Now the next step. to add Multible Alliances "2-3" to post in DIFFERENT Channels.

Thank you for your time

**Comment by shibdib** [comment]
Doable

**Comment by shibdib** [comment]
just trying to figure out how worthwhile this would be, when would something like this be helpful?

**Comment by shoyumimura** [comment]
Example:
1. Corp does Normal PvP get kill in the "Killmail" Channel
2. Corp would like to see all kills that are over 10billion (like in Zkillboard) in a "DIFFERENT" Channel.
3. Or think it like this: More than 3 Corps on the same Discord want all their own killboard Channel. 

Our Problem: 
1.Atm, it is not possible to see more than Corp and/or Alliance Killmail in "ONE" Channel Only.
2.Atm it is not possible to add :  https://zkillboard.com/kills/10b/   (for Kills)

Hope I could Help

**Comment by shibdib** [comment]
So a separate channel for big kills I can see

but the multi corp thing, isn't that just covered by an alliance killmail lookup?

**Comment by shoyumimura** [comment]
1, Yep the extra Bigkills Channel is the Important one (most Wanted in our Alliance Discord).
2. For alliances yes, but our Discord "Mainchannel" is a Group of 4 Corps all with their unique playstyle (pvp vise). So if possibl we would like to have 4 seperat channels ... Thank you

**Comment by shibdib** [comment]
added in the latest push

**Comment by shoyumimura** [comment]
Very nice ... will Update in 2 days to the new build ... 
Is there a way to add the 10billion+ kills to the bot ? Because normalis a CorpID or AllianceID in the Config file, but the 10b+ kills are like this " https://zkillboard.com/kills/10b/ ".. how to addd this in the Config ?

But still thank you very very much for the time invested... Work good so far :P

**Comment by shoyumimura** [comment]
bump

**Comment by shibdib** [comment]
so you want all 10b kills? Like non group specific?

**Comment by shoyumimura** [comment]
if possible . I Can´t add them myself, because the bot does not recognise the "https://zkillboard.com/kills/10b/" as an CorpID or AllianceID
