### ISSUE TITLE
Failure: There are no roles available for your corp/alliance.

### ISSUE THREAD

**Issue by mthomas92868** [shibdib/Dramiel#64]
Hello, i have created a new bot on a new ubuntu server, it has no issue removing roles from people, but everytime we try to add i get Failure: There are no roles available for your corp/alliance., i'm not sure what this error means, doing a little debuging seems it cannot get any roles back. any help would be great thank you.

PHP Notice:  Trying to get property of non-object in /opt/Dramiel/src/plugins/onMessage/auth.php on line 147
PHP Notice:  Trying to get property of non-object in /opt/Dramiel/src/plugins/onMessage/auth.php on line 148

**Comment by Maxcraft90** [comment]
Did you put the role within "" in the config.php?
For example "@member".
Ofc the role name needs to match your server.

**Comment by mthomas92868** [comment]
i have a role called "MEMBER" on my Discord...i even tried with the "@" sign and stills same issue, and yes in my config

http://prntscr.com/csqgob

http://prntscr.com/csqgub

same error on DramielError
PHP Notice:  Trying to get property of non-object in /opt/Dramiel/src/plugins/onMessage/auth.php on line 147
PHP Notice:  Trying to get property of non-object in /opt/Dramiel/src/plugins/onMessage/auth.php on line 148

I'm using ubuntu 16.04 with php 7

**Comment by shibdib** [comment]
The bot isn't written with php7 in mind although it might still work,
haven't had a chance to test it. I'll have computer access come Friday
hopefully (rl deployed atm) so until then the other Bros will have to help
you troubleshoot

**Comment by Maxcraft90** [comment]
put the corpID within quotation marks, maybe this will help. just looking on how I set it up. 

Ofc it can be a problem because of the php 7. is there a possibility for you to downgrade? I am currently running on 5.6.23 and it works like a charm.

**Comment by mthomas92868** [comment]
Hello thanks for all this help, so i have downgrade to PHP 5.6.23 still same issue. Seem everytime i try to run "!auth 57f5d130d6f3c" it crashes the bot, i guess i can try another version of linux
@Maxcraft90 what version of linux are you running?

**Comment by shibdib** [comment]
What's the error log say

**Comment by mthomas92868** [comment]
same error as last time, PHP Notice: Trying to get property of non-object in /opt/Dramiel/src/plugins/onMessage/auth.php on line 147
PHP Notice: Trying to get property of non-object in /opt/Dramiel/src/plugins/onMessage/auth.php on line 148

when it trying to get the roles, and members its failing...i have deleted the VM, gonna recreate it VM with 5.6 instead...see if make difference

**Comment by shibdib** [comment]
A notice isn't a crash usually. What do the other logs say

**Comment by Maxcraft90** [comment]
@mthomas92868 14.04.5 LTS
The error on line 147 is the same that I once had...you probably do not have the guild ID (server ID) set in the config.
Also one question. Are you running on the newest version of the bot?

**Comment by mthomas92868** [comment]
Hello All, thanks for all the help me running 14.04.5 with php 5.6 seems to be working now. Thanks agian
