### ISSUE TITLE
Fleet up Not broadcasting

### ISSUE THREAD

**Issue by CokkocZateki** [shibdib/Dramiel#65]
hi
all functions seem to work well. however no fleet up broadcasts worked

only warning message i get in the logs

```
`PHP` Warning:  Invalid argument supplied for foreach() in /home/Dramiel/src/plugins/onTick/fleetUpOperations.php on line 103
PHP Warning:  Invalid argument supplied for foreach() in /home/Dramiel/src/plugins/onTick/fleetUpOperations.php on line 103
PHP Warning:  Invalid argument supplied for foreach() in /home/Dramiel/src/plugins/onTick/fleetUpOperations.php on line 103
PHP Warning:  Invalid argument supplied for foreach() in /home/Dramiel/src/plugins/onTick/fleetUpOperations.php on line 152``
```

**Comment by CokkocZateki** [comment]
Has anyone managed to get this working. Ive added all the details. Updated supervisor and restarted Dramiel.

**Comment by scopehs** [comment]
What php version are you running?

**Comment by CokkocZateki** [comment]
not home at the moment to confirm but i think it was 5.7

**Comment by CokkocZateki** [comment]
ahh this is frustrating. every other function on the bot works except fleet up

**Comment by Maxcraft90** [comment]
if i look at the error it seems that it maybe didn't pull your user ID correctly? in those lines the json of the api will be pulled and decoded, so i suggest checking if the link to the api is correct and the id's are all set correctly.

**Comment by CokkocZateki** [comment]
Hi

I've deleted and created multiple apps etc for fleet and still get the same
result :(

**Comment by CokkocZateki** [comment]
@shibdib any suggestions

**Comment by shibdib** [comment]
Still deployed without an actual computer. Should have one tmw hopefully
and I'll give these issues a closer look

**Comment by CokkocZateki** [comment]
Super Thx mate

**Comment by Maxcraft90** [comment]
so I just set it up myself and it works like a charm. running on php 5.6 and 14.04. did you get your group id correctly and registered the API onto the application of MrTwinkie?

**Comment by CokkocZateki** [comment]
Yup. I can try it again. But I tried different  options to make sure it was
correct

On 13 Oct 2016 21:03, "Maxcraft90" notifications@github.com wrote:

so I just set it up myself and it works like a charm. running on php 5.6
and 14.04. did you get your group id correctly and registered the API onto
the application of MrTwinkie?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/shibdib/Dramiel/issues/65#issuecomment-253607497, or mute
the thread

**Comment by Maxcraft90** [comment]
a screenshot would help a lot :)

**Comment by CokkocZateki** [comment]
I don't think a screen shot will help. If I'm typing in the wrong info then
it's not viewable. So if someone got a link I can try to be 1000% sure then
I'm sure that will be better.

On 13 Oct 2016 21:35, "Maxcraft90" notifications@github.com wrote:

a screenshot would help a lot :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/shibdib/Dramiel/issues/65#issuecomment-253615580, or mute
the thread

**Comment by CokkocZateki** [comment]
the link im using. with my app and api details etc

http://api.fleet-up.com/Api.svc/3xampl3App/12345/G5hdw34hSDhehdFD/MyGroupMemberships

**Comment by Maxcraft90** [comment]
sorry read that wrong

hmm it's crazy that it doesn't work. do you have any other errors showing in the log?

**Comment by CokkocZateki** [comment]
thats what i did and it spat out the code for group ID... but broadcast
doesnt work :(

**Comment by Maxcraft90** [comment]
![image](https://cloud.githubusercontent.com/assets/20978852/19365411/e2bce870-9192-11e6-93fc-cd61cdc95557.png)
that's what i got after posting a test op. it pinged 15 minutes before the op. 
did you also uncomment the fleet-up option in the config.php?

**Comment by CokkocZateki** [comment]
yup still nothing. fleetup is uncommented. all intergars are correct.

**Comment by CokkocZateki** [comment]
anyone able to assist me pretty please :(

**Comment by shibdib** [comment]
I was honestly considering removing fleet up support -_-

**Comment by CokkocZateki** [comment]
nooooo pls dont.

**Comment by shibdib** [comment]
pastebin your config file plz (remove/replace api's and whatnot)
