### ISSUE TITLE
Feature Request: multiply keys from differend accounts, faster notifcation posting?

### ISSUE THREAD

**Issue by KongGal** [shibdib/Dramiel#72]
Is it possible to make so you can apply more than 1 key from differend accounts and have it fetch notifications more often
like 1 key = fetch ever 30 min, 2 keys = every 15 min, 3 keys every 10m
and have config options to define how often it should scan and how many keys is suppiled
Like 
"keys" => "#", // Numbers of keys you have supplied
"interval" => "#" // how often in min it should try and fetch notifications

**Comment by shibdib** [comment]
Mmm this is doable
