### ISSUE TITLE
Feature Request: RRS feed

### ISSUE THREAD

**Issue by KongGal** [shibdib/Dramiel#73]
a plugin which could read RRS feeds such as new_eden_news_bot on reddit which will read from defined RRS feeds

**Comment by shibdib** [comment]
Should be easy enough to add

**Comment by shibdib** [comment]
Little buggy right now, will close when I fix some issues

**Comment by KongGal** [comment]
I found this one which is the one i use right now, maybe you can get a bit of tips from

https://github.com/freiheit/discord_feedbot

**Comment by shibdib** [comment]
The plugin I wrote works, I just need to make it not post old articles on the first run and add atom feed support

**Comment by shibdib** [comment]
k should no longer repeat old posts. Still no atom support yet
