### ISSUE TITLE
Notifications update

### ISSUE THREAD

**Issue by CokkocZateki** [shibdib/Dramiel#75]
Hi Everyone.

We declared war again some ppl. however the bot displays the below. Is it possible to add who we wardeccing or who is wardeccing us?

@everyone | War declared by Wrecking Machine.. Fighting begins in roughly 24 hours.

Thanks

**Comment by shibdib** [comment]
So you declared the war?

**Comment by CokkocZateki** [comment]
yes. but it doesnt say against who. the same when war is declared on us. it doesnt show the group

**Comment by shibdib** [comment]
You were the group who declared the war?

**Comment by CokkocZateki** [comment]
yes @shibdib

**Comment by shibdib** [comment]
This should be fixed*™

There's no way to differentiate from the api who the notification is going
to without adding more shit to the config. So I changed the verbiage at a
bit
