### ISSUE TITLE
getKillmail {$shipName} and {$systemName} bugged in lastest update

### ISSUE THREAD

**Issue by KongGal** [shibdib/Dramiel#77]
my bot is printing shipName and systemName as unknown after updating

http://prntscr.com/cxuj7s first hit is before i updated and the 2nd is after i updated

**Comment by shibdib** [comment]
will fix this shortly

**Comment by shibdib** [comment]
Fixed

**Comment by KongGal** [comment]
did you push the fix yet? don't see any updates to the code?

**Comment by shibdib** [comment]
https://github.com/shibdib/Dramiel/commit/8655128d4b3894a5fe4998c7b098d129d59809ad
