### ISSUE TITLE
Feature Request: Fleet up

### ISSUE THREAD

**Issue by CokkocZateki** [shibdib/Dramiel#79]
Hi Folks.

Is it possible to have the Dramiel work that if u do !fleet or something similar it can display all the fleetup fleets?

It would be extremly useful for my group since we use fleetup alot

**Comment by shibdib** [comment]
Doable added to #74

**Comment by HunHawk** [comment]
Edit you setting file:
insert this in enabledPlugins section:
`"ops", //show upcoming fleet up operations`
add this to end of Plugins section:
`//shows upcoming fleet up operations
    "ops" => array(
        "channelID" => 0, //channel id to ping about operations
        "userID" => 0, //fleet up user id
        "groupID" => 0, //fleet up group id
        "apiKey" => "", //fleet up api code, link to application Dramiel Bot
        "channelID" => 0 //If you want to restrict upcoming ops from working in a channel, put that channel's ID here.
    ),`
Upload the attached ops.php file into /src/plugins/onMessage folder.
Restart the bot to apply the changes.
Usage: !ops
[ops.zip](https://github.com/shibdib/Dramiel/files/559881/ops.zip)

**Comment by shibdib** [comment]
@HunHawk feel free to make a pull of that and I'll integrate it officially

**Comment by HunHawk** [comment]
I don't know how to do it, and don't want to ruin anything. That's why I manually edit my files (e.g. price.php).

**Comment by CokkocZateki** [comment]
I can gladly test it tonight
