### ISSUE TITLE
BUG: API Error

### ISSUE THREAD

**Issue by Maxcraft90** [shibdib/Dramiel#80]
Hello guys

Currently I am always getting an API Error if someone wants to auth. Is anyone of you expecting the same? Config is unchanged since forever and yeah...
ErrorLog shows an Error where the auth.php in OnMessage should show the ErrorMessage if there is an XML-Error.

**Comment by shibdib** [comment]
have u done a pull in the last 3 hours? i pushed out a fix for an api issue

**Comment by Maxcraft90** [comment]
Works now. Thx
