### ISSUE TITLE
Message commands reply not shown

### ISSUE THREAD

**Issue by HunHawk** [shibdib/Dramiel#84]
Everything is up to date.
The message commands works (except corp, char and fleetupops), I saw the replies in the DB file, but not shown in discord. The onTick plugins replies are shown, the bot responds the ping command.

Dramiel-error.log:
PHP Notice:  Undefined index: fleetUpOps in /var/www/Dramiel/src/plugins/onMessage/fleetUpOps.php on line 72
PHP Notice:  Undefined index: fleetUpOps in /var/www/Dramiel/src/plugins/onMessage/fleetUpOps.php on line 73
PHP Notice:  Undefined index: fleetUpOps in /var/www/Dramiel/src/plugins/onMessage/fleetUpOps.php on line 74
PHP Warning:  Missing argument 3 for queueReplyMessage(), called in /var/www/Dramiel/src/plugins/onMessage/charInfo.php on line 117 and defined in /var/www/Dramiel/src/lib/queueManagement.php on line 53
PHP Notice:  Undefined variable: message in /var/www/Dramiel/src/lib/queueManagement.php on line 55
PHP Warning:  Invalid argument supplied for foreach() in /var/www/Dramiel/src/plugins/onMessage/fleetUpOps.php on line 118

DramielLog.log (when exec !ops command):
[2016-11-05 14:51:17] Dramiel.ERROR: Error: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: replysQueue.message [] []

Op. system: Ubuntu 16.04
PHP: 7.0

**Comment by shibdib** [comment]
should be fixed, reverted a change that was working but ended up fucking the bot

**Comment by HunHawk** [comment]
The bot now answers for commands except for fleetupops:
dramielError.log:
PHP Notice:  Undefined index: fleetUpOps in /var/www/Dramiel/src/plugins/onMessage/fleetUpOps.php on line 72
PHP Notice:  Undefined index: fleetUpOps in /var/www/Dramiel/src/plugins/onMessage/fleetUpOps.php on line 73
PHP Notice:  Undefined index: fleetUpOps in /var/www/Dramiel/src/plugins/onMessage/fleetUpOps.php on line 74
PHP Warning:  Invalid argument supplied for foreach() in /var/www/Dramiel/src/plugins/onMessage/fleetUpOps.php on line 116

The char and corp commands never find data, allways get this:
Charinfo: Error: no data available
Corpinfo: Error: No data available for that group.

**Comment by shibdib** [comment]
not a bot error, eve-kill is down which is where it pulls alot of data from for those 2. Added a more descriptive message in the latest push
