### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by G0wd** [shibdib/Dramiel#85]
Hello,

The bot is not working any more after the last pull.

> git pull
> Already up-to-date.

> PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/home/discord/dramiel/src/lib../../log" and its not buildable: File exists in /home/discord/dramiel/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
> Stack trace:
> #0 /home/discord/dramiel/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
> #1 /home/discord/dramiel/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)
> #2 /home/discord/dramiel/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
> #3 /home/discord/dramiel/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, 'could not find ...', Array)
> #4 /home/discord/dramiel/src/lib/Db.php(50): Monolog\Logger->error('could not find ...')
> #5 /home/discord/dramiel/src/lib/Db.php(67): openDB('/home/discord/d...')
> #6 /home/discord/dramiel/src/lib/updateDramielDB.php(90): dbQ in /home/discord/dramiel/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 161

PHP 7.0.12 (cli) (built: Oct 14 2016 05:48:15) ( NTS )
Archlinux

Any ideas?

Thanks in advance for the help.

**Comment by KongGal** [comment]
looks like its a permission issue.
try and go to /home/discord/dramiel and "chmod 777 -R src"
its trying to make a log folder in /src/lib but it can't so most likely permission issue

There is no existing directory at "/home/discord/dramiel/src/lib../../log" and its not buildable:

**Comment by G0wd** [comment]
Hello,

I tried already, I even tried to chmod 777 the whole directory with no success.

It was working fine before the last pull so I'm not sure that is a permission problem.

Any other ideas?

**Comment by G0wd** [comment]
Problem solved, apparently it was a missing dependency issue with sqlite3.

My bad.
