### ISSUE TITLE
Help with killmails

### ISSUE THREAD

**Issue by G0wd** [shibdib/Dramiel#87]
> [2016-11-07 00:03:33] Dramiel.ERROR: Killmails: UPDATE YOUR CONFIG TO RECEIVE KILLMAILS [] []

> "getKillmails", // show corp killmails in a chat channel

>     //Killmail posting
>     "getKillmails" => array(
>         "channel" => 240486784580889473, //killmails post to this channel
>         "bigKill" => null, //Set an isk amount you'd like to consider a high value kill, will alert the channel if any kills/losses hit this amount. (Leave as null if you don't want this feature)
>         "corpID" => 263585335, //corpid for killmails
>         "allianceID" => 0, //allianceid for killmails (Leave as 0 if using it for a corp)
>         "lossMails" => "true", //set as true to post both kills and losses, false to post only kills.
>         "spamAmount" => 10, //Max amount of kills the bot will post every 10 minutes. Default is 15 and won't get the bot kicked for spamming.
>         "startMail" => 57010648, //Put the zkill killID of your latest killmail. Otherwise it will pull from the beginning of time.
>     ),

Is There something else I need to set in order to get the killmails?

Is an API key needed?

Ty for the help

**Comment by shibdib** [comment]
Mails have been updated a bit look in your config.new.php for the new format
