### ISSUE TITLE
Only post expensive killmails

### ISSUE THREAD

**Issue by G0wd** [shibdib/Dramiel#92]
Hi,

Is it possible to only post expensive killmails ?

Or set a limit for regular killmails in the config like 100M to avoid spam when 200 frigates dies.

Ty for the help.

**Comment by Maxcraft90** [comment]
this option is available in the config.php :) check again

**Comment by G0wd** [comment]
Well, I know how to show corporation expensive killmails, what I want is to show ONLY corporation expensive killmails, and deactivate regular corporation killmails.

**Comment by shibdib** [comment]
I can add the option for a minimum isk threshold fairly easily. Will get that done in a little bit

**Comment by G0wd** [comment]
Awesome, thanks.
