### ISSUE TITLE
Fatal error when activating killmails

### ISSUE THREAD

**Issue by G0wd** [shibdib/Dramiel#93]
> PHP Fatal error:  Uncaught Error: Call to a member function sendMessage() on null in /home/discord/dramiel/Dramiel.php:171
> Stack trace:
> #0 [internal function]: {closure}(Object(React\EventLoop\Timer\Timer))
> #1 /home/discord/dramiel/vendor/react/event-loop/src/Timer/Timers.php(90): call_user_func(Object(Closure), Object(React\EventLoop\Timer\Timer))
> #2 /home/discord/dramiel/vendor/react/event-loop/src/StreamSelectLoop.php(177): React\EventLoop\Timer\Timers->tick()
> #3 /home/discord/dramiel/vendor/team-reflex/discord-php/src/Discord/Discord.php(1228): React\EventLoop\StreamSelectLoop->run()
> #4 /home/discord/dramiel/Dramiel.php(242): Discord\Discord->run()
> #5 {main}
>   thrown in /home/discord/dramiel/Dramiel.php on line 171

Any ideas?

**Comment by Maxcraft90** [comment]
does this come immediately when you start the bot? if not, does your bot have rights to send to the channel?

**Comment by G0wd** [comment]
Yes, it has admin permissions on discord.

I fixed the problem by deleting the sqlite database.
